version: "3"

services:
  mongo:
    image: mongodb/mongodb-community-server:6.0.6-ubi8
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=test
    volumes:
      - ./mongoData:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - go-server

  go-app:
    depends_on:
      mongo:
        condition: service_healthy
    build:
      context: ./server
      dockerfile: ../docker/go/Dockerfile
    ports:
      - 4321:4321
      - 2345:2345
    environment:
      - MONGO_DB_URI=mongodb://root:password@mongo:27017/
      - SERVER_PORT=4321
    volumes:
      - ./server:/app
    networks:
      - go-server

  migrate:
    image: migrate/migrate:v4.17.1
    volumes:
      - ./migrations/sql:/migrations
    networks:
      - go-server

networks:
  go-server:
    driver: bridge
