version: "3"

services:
  postgres:
    image: postgres:14
    ports:
      - 3432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=go_test
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgData:/var/lib/postgresql/data
    networks:
      - go-server

  go-app:
    depends_on:
      - postgres
    build:
      context: ./server
      dockerfile: ../docker/dev/Dockerfile
    ports:
      - 4321:4321
    environment:
      - DB_HOST=postgres
      - DB_PORT=3432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=go_test
      - DB_MAX_RETRIES=10
      - SERVER_PORT=4321
    volumes:
      - ./server:/app
    networks:
      - go-server

networks:
  go-server:
    driver: bridge
