version: "3"

services:
  postgres:
    image: postgres:14
    ports:
      - 3432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=go_test
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgData:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d go_test"]
      interval: 5s
      timeout: 5s
      retries: 0
    networks:
      - go-server

  mongo:
    image: mongodb/mongodb-community-server:6.0.6-ubi8
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=nosubjects_config
    volumes:
      - ./mongoData:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/nosubjects_config --quiet
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - go-server

  go-app:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: ./server
      dockerfile: ../docker/dev/Dockerfile
    ports:
      - 4321:4321
      - 2345:2345
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=go_test
      - MONGO_DB_URI=mongodb://root:password@mongo:27017/
      - SERVER_PORT=4321
    volumes:
      - ./server:/app
    networks:
      - go-server

networks:
  go-server:
    driver: bridge
